server:
  port: 8088
#logging:
#  file:
#    path: D:/logs/springboot
#  config: classpath:config/logback-spring.xml
#  level:
#    root: info

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hqyj_cn0?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 20020320
    druid:
      initial-size: 3
      max-active: 20
      max-wait: 60000
      min-idle: 3
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #采集数据库监控的数据
      web-stat-filter:
        url-pattern: /*
        enabled: true
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      #展示监控信息
      stat-view-servlet:
        url-pattern: /druid/*
        allow: 127.0.0.1
        reset-enable: false
        #是否开启，设置为true才能打开监控页面
        enabled: true
        #druid监控登录页面的用户名
        login-username: root
        #druid监控登录页面的密码
        login-password: root
  redis:
    host: localhost
    port: 6379
    #redis中 默认16个数据库 编号索引0-15
    database: 0
    #密码,默认密码为空,如果要设置密码需要修改redis的配置文件
    #password: 123456
    timeout: 2000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 2000ms
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  #使用redis方式实现cache
  cache:
    type: redis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.hqyj.*.*.entity
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ASSIGN_ID:"mybatisplus分配ID，Long，Integer，String", ASSIGN_UUID:"分配UUID，String";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      #filed-strategy在高版本被废弃(3.1.2以后)
      #filed-strategy: NOT_EMPTY
      insert-strategy: not_empty
      select-strategy: not_empty
      update-strategy: not_empty
      #刷新mapper 调试神器
      refresh-mapper: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
#自定义配置
system:
  #静态资源文件目录
  upload-filepath: D:/touxiang/
  #浏览静态资源的url路径
  view-path: /view
  expire-time: 36000000